Gerando boletos Unicred
eduardokum/laravel-boleto pull request #614
Opened 2021-03-16 23:50 UTC by ricardor2soft

2021-03-17 00:15 UTC, ricardor2soft commented
Estava fazendo errado, estava enviando para o master.

2021-03-17 09:59 UTC, eduardokum requested changes

2021-03-17 09:59 UTC, eduardokum commented on src/Boleto/Banco/Bradesco.php
> +    protected $especiesCodigo = [
Você tem que atualizar seu repositorio antes de enviar esse PR, esta enviado codigo desatualizado

2021-03-17 09:59 UTC, eduardokum commented on composer.json
> +    "name": "r2soft/laravel-boleto",
Não pode atualterar o nome do projeto no composer

2021-03-18 11:31 UTC, ricardor2soft commented on composer.json
> +    "name": "r2soft/laravel-boleto",
Resolvido, confere por favor.

2021-04-26 16:38 UTC, closed without merging