Feat: Implementação de dias de carencia na multa
eduardokum/laravel-boleto pull request #738
Opened 2024-03-13 20:47 UTC by MarquesSouza

## Oque foi feito!
Adição da propriedade multaApos para permitir customização de quantos dias após o vencimento e aplicado a multa. Fornecendo assim a opção para o cliente definir uma carência em dias da aplicação da multa.

## Commits list
feat: Implementação de dias de carencia na multa. Adicionado metodos setMultaApos() e getMultaApos() para permitir adicionar dias apos o vencimento

2024-04-29 09:27 UTC, eduardokum requested changes
Após ajustes aprovo, Obrigado.

2024-05-27 14:58 UTC, MarquesSouza commented
Aplicado correção conforme solicitado.

2024-05-28 16:32 UTC, eduardokum requested changes

2024-05-28 16:32 UTC, eduardokum commented on src/Cnab/Remessa/Cnab240/Banco/Bancoob.php
> +        $this->add(67, 74, $boleto->getMulta() > 0 ?  $boleto->getDataVencimento()->copy()->addDay($boleto->getMultaApos())->format('dmY') : '00000000');
todos esse addDay precisam ser addDays() se não, addDay nao tem argumento e sempre incrementa em 1

2024-05-28 17:49 UTC, MarquesSouza commented on src/Cnab/Remessa/Cnab240/Banco/Bancoob.php
> +        $this->add(67, 74, $boleto->getMulta() > 0 ?  $boleto->getDataVencimento()->copy()->addDay($boleto->getMultaApos())->format('dmY') : '00000000');
Aplicado correções nos arquivos de remessa 240 que estavam com este error.

2024-05-28 18:21 UTC, eduardokum approved these changes

2024-06-17 13:58 UTC, merged