Feat: Implementação da API da Unicred
eduardokum/laravel-boleto pull request #739
Opened 2024-03-28 01:34 UTC by mfgustav0

Implementação da API V2 da Unicred.

2024-04-29 09:24 UTC, eduardokum requested changes
Após ajustes aceito. Obrigado

2024-04-29 09:24 UTC, eduardokum commented on src/Api/AbstractAPI.php
> +    protected function post($url, array $post, $raw = false, $clear=true)
Essa opção deve ser false por padrao para não mexer nos bancos que ja estão funcionando

2024-04-29 09:24 UTC, eduardokum commented on src/Contracts/Pessoa.php
> +    public function getNomeFantasia();
Deixe essa opção somente na classe concreta, pois quem implementa essa interface vai quebrar por adicionar esse campo a mais.

2024-04-30 15:00 UTC, mfgustav0 commented on src/Contracts/Pessoa.php
> +    public function getNomeFantasia();
Já ajustei para deixar apenas na classe concreta.

2024-04-30 15:03 UTC, mfgustav0 commented on src/Api/AbstractAPI.php
> +    protected function post($url, array $post, $raw = false, $clear=true)
Eu deixei como true pois por padrão no metodo é limpado as strings do Post, ai neste caso iria influenciar nos outros bancos.

Ainda assim ajusto isso?

2024-06-17 13:55 UTC, eduardokum approved these changes

2024-06-17 13:55 UTC, merged